import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

const CeraCY = localFont({
    src: [
        {
            path: "./fonts/Cera CY Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/Cera CY Bold.ttf",
            weight: "700",
            style: "normal",
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={CeraCY.className}>{children}</body>
        </html>
    );
}
