import type { Metadata } from "next";
import "./globals.css";

import { Background } from "@/app/(index)/components/background";
import { Cursor } from "@/components/cursor";
import { ThemeProvider } from "@/providers/theme-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={{ fontFamily: "Cera CY" }}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                >
                    <Cursor />
                    <Background />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
