import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from "next/font/google";

import Background from "@/components/background";
import { ThemeProvider } from "@/providers/theme-provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                >
                    <Background />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
